#!/bin/sh

set -e

[ -f /etc/default/sdp-server ] && . /etc/default/sdp-server

IS_UPGRADE=false


case "$1" in
	configure)
	[ -z "$SDP_USER" ] && SDP_USER="sdp"
	[ -z "$SDP_GROUP" ] && SDP_GROUP="sdp"
	if ! getent group "$SDP_GROUP" > /dev/null 2>&1 ; then
	    addgroup --system "$SDP_GROUP" --quiet
	fi
	if ! id $SDP_USER > /dev/null 2>&1 ; then
	    adduser --system --home /usr/share/sdp --no-create-home \
		--ingroup "$SDP_GROUP" --disabled-password --shell /bin/false \
		"$SDP_USER"
	fi

	# Set user permissions on /var/log/sdp, /var/lib/sdp
	mkdir -p /var/log/sdp /var/lib/sdp
	chown -R $SDP_USER:$SDP_GROUP /var/log/sdp /var/lib/sdp
	chmod 755 /var/log/sdp /var/lib/sdp

  # copy user config files
  if [ ! -f $CONF_FILE ]; then
    cp /usr/share/sdp/conf/sample.ini $CONF_FILE
    cp /usr/share/sdp/conf/ldap.toml /etc/sdp/ldap.toml
  fi

  if [ ! -f $PROVISIONING_CFG_DIR ]; then
    mkdir -p $PROVISIONING_CFG_DIR/dashboards $PROVISIONING_CFG_DIR/datasources
    cp /usr/share/sdp/conf/provisioning/dashboards/sample.yaml $PROVISIONING_CFG_DIR/dashboards/sample.yaml
    cp /usr/share/sdp/conf/provisioning/datasources/sample.yaml $PROVISIONING_CFG_DIR/datasources/sample.yaml
  fi 

	# configuration files should not be modifiable by sdp user, as this can be a security issue
	chown -Rh root:$SDP_GROUP /etc/sdp/*
	chmod 755 /etc/sdp
	find /etc/sdp -type f -exec chmod 640 {} ';'
	find /etc/sdp -type d -exec chmod 755 {} ';'

  # If $1=configure and $2 is set, this is an upgrade
  if [ "$2" != "" ]; then
    IS_UPGRADE=true
  fi

  if [ "x$IS_UPGRADE" != "xtrue" ]; then
    if command -v systemctl >/dev/null; then
      echo "### NOT starting on installation, please execute the following statements to configure sdp to start automatically using systemd"
      echo " sudo /bin/systemctl daemon-reload"
      echo " sudo /bin/systemctl enable sdp-server"
      echo "### You can start sdp-server by executing"
      echo " sudo /bin/systemctl start sdp-server"
    elif command -v update-rc.d >/dev/null; then
      echo "### NOT starting sdp-server by default on bootup, please execute"
      echo " sudo update-rc.d sdp-server defaults 95 10"
      echo "### In order to start sdp-server, execute"
      echo " sudo service sdp-server start"
    fi
  elif [ "$RESTART_ON_UPGRADE" = "true" ]; then

    echo -n "Restarting sdp-server service..."

    if command -v systemctl >/dev/null; then
      systemctl daemon-reload
      systemctl restart sdp-server || true
    elif [ -x /etc/init.d/sdp-server ]; then
      if command -v invoke-rc.d >/dev/null; then
        invoke-rc.d sdp-server restart || true
      else
        /etc/init.d/sdp-server restart || true
      fi
    fi
    echo " OK"

	fi
	;;
esac
